# local configuration

[app]
port = 17452
host = "localhost"
env = "local"
name = "go-microservice"

[database]
name = "go_microservice"
username = "postgres"
password = "fx123nm"
host = "localhost"
port = "5432"

[redis]
host = "localhost"
port = "6379"

[jaeger]
host = "localhost"
port = "6831"

[another_rpc]
host="localhost"
port="17445"